import type { NextPage } from "next"
import Head from "next/head"
import s from "styles/Home.module.css"
import { User } from "components"

const Home: NextPage = () => {
    return (
        <div className={s.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={s.main}>
                <User
                    photo="/vercel.svg"
                    name="Javier Castro"
                    gender="Male"
                    location="Santiago"
                />
            </main>
        </div>
    )
}

export default Home
