import Head from "next/head";
import s from "styles/Home.module.css";
import { Character } from "components";
import { Layout } from "common/components";
import { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Character
        photo="/vercel.svg"
        name="Javier Castro"
        gender="Male"
        location="Santiago"
      />
    </div>
  );
};

Home.getLayout = (page) => <Layout>{page}</Layout>;

export default Home;
